# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            # No pattern means every path is behind this firewall
            anonymous:
                secret: '%env(SECRET)%'
            form_login:
                login_path: adherent_login
                check_path: adherent_login_check

                default_target_path: events_index
                always_use_default_target_path: true

                username_parameter: _adherent_email
                password_parameter: _adherent_password
                csrf_parameter: _adherent_csrf
                csrf_token_id: authenticate_adherent

    access_control:
        - { path: '^/espace-adherent/mon-profil', roles: [ROLE_ADHERENT] }
