services:
    app.webpack_asset_extension:
        class: AppBundle\Twig\WebpackAssetExtension
        public: false
        arguments:
            - "@twig.extension.assets"
            - "%kernel.environment%"
            - "%assets_hash%"
        tags:
            - { name: twig.extension }
